# Generated by Django 5.2.1 on 2025-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_course_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comp',
            field=models.CharField(choices=[('N', 'Ninguno'), ('A', 'Formación Básica'), ('B', 'Formación Especializada'), ('C', 'Formación Profesional y Otros'), ('D', 'Est.Gen.: Capacidades de Aprendizaje'), ('E', 'Est.Gen.: Form.Humanist.Ident. y Ciudadanía'), ('F', 'Estudios Específicos'), ('G', 'Estudios de Especialidad')], default='N', max_length=2),
        ),
    ]
