# Generated by Django 5.2.1 on 2025-07-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.academicunit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.curriculum'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.term'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hl',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ht',
        ),
        migrations.RemoveField(
            model_name='course',
            name='htp',
        ),
    ]
