# Generated by Django 5.2.1 on 2025-07-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='hs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='ht',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='htp',
            field=models.IntegerField(default=0),
        ),
    ]
