# Generated by Django 5.2.1 on 2025-07-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_course_hl_course_hours_course_hp_course_hs_course_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(default=0),
        ),
    ]
